# ./vendor/bin/ece-docker 'build:compose' --host='magento-docker.local' --mode=developer --mailhog-smtp-port=1025 --mailhog-http-port=8025
version: '2.1'
services:
  db:
    hostname: db.magento-docker.local
    image: 'mariadb:10.3'
    shm_size: 2gb
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
    ports:
      - '3306'
    volumes:
      - '.:/app:delegated'
      - 'magento-magento-db:/var/lib/mysql'
    healthcheck:
      test: 'mysqladmin ping -h localhost -pmagento2'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - db.magento-docker.local
  redis:
    hostname: redis.magento-docker.local
    image: 'redis:5.0'
    volumes:
      - '.:/app:delegated'
    ports:
      - 6379
    sysctls:
      net.core.somaxconn: 1024
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      magento:
        aliases:
          - redis.magento-docker.local
  elasticsearch:
    hostname: elasticsearch.magento-docker.local
    image: 'magento/magento-cloud-docker-elasticsearch:7.5-1.3.2'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    networks:
      magento:
        aliases:
          - elasticsearch.magento-docker.local
  fpm:
    hostname: fpm.magento-docker.local
    image: 'magento/magento-cloud-docker-php:8.1-fpm-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - fpm.magento-docker.local
    depends_on:
      db:
        condition: service_healthy
  web:
    hostname: web.magento-docker.local
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    environment:
      - WITH_XDEBUG=0
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
    networks:
      magento:
        aliases:
          - web.magento-docker.local
    depends_on:
      fpm:
        condition: service_started
  varnish:
    hostname: varnish.magento-docker.local
    image: 'magento/magento-cloud-docker-varnish:6.2-1.3.2'
    networks:
      magento:
        aliases:
          - varnish.magento-docker.local
    depends_on:
      web:
        condition: service_started
  tls:
    hostname: tls.magento-docker.local
    image: 'magento/magento-cloud-docker-nginx:1.19-1.3.2'
    extends: generic
    networks:
      magento:
        aliases:
          - magento-docker.local
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024
      - UPSTREAM_HOST=varnish
      - UPSTREAM_PORT=80
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      varnish:
        condition: service_started
  generic:
    hostname: generic.magento-docker.local
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    env_file: ./.docker/config.env
    environment:
      - MAGENTO_RUN_MODE=developer
      - 'PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pcntl pdo_mysql soap sockets sysvmsg sysvsem sysvshm opcache zip xsl sodium redis'
  build:
    hostname: build.magento-docker.local
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento-build:
        aliases:
          - build.magento-docker.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  deploy:
    hostname: deploy.magento-docker.local
    image: 'magento/magento-cloud-docker-php:8.1-cli-1.3.2'
    extends: generic
    volumes:
      - '.:/app:delegated'
    networks:
      magento:
        aliases:
          - deploy.magento-docker.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  mailhog:
    hostname: mailhog.magento-docker.local
    image: 'mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      magento:
        aliases:
          - mailhog.magento-docker.local
volumes:
  magento-magento-db: {  }
networks:
  magento:
    driver: bridge
  magento-build:
    driver: bridge
